### ISSUE TITLE
Request for Official Release of Scheduled Email Functionality

### ISSUE THREAD

**Issue by Rolet** [resendlabs/resend-java#37]
Hello Resend Team,

Thank you for providing the Java SDK in the repository—it’s a great addition! I noticed that while the code is available here, there hasn’t been an official release yet (e.g., on Maven Central). An official release would make it much easier to integrate and manage the SDK as a dependency in Java projects.

I’m particularly interested in using the SDK’s scheduled email functionality and would appreciate any information about its stability. Is this feature production-ready, or is it still in development? Any insights on its current status would be very helpful.

Would it be possible to create a release version for the SDK? This would help streamline integration and updates for all users relying on it, especially those looking to implement scheduling.

Thank you again for your work

**Comment by kewynakshlley** [comment]
I didn't get it. This SDK is available on Maven Central. The SDK was officially released, and all releases are versioned in Maven Central.

**Comment by Rolet** [comment]
To clarify, my question is specifically about the scheduling email functionality. I noticed that this feature is available in the main branch but hasn’t been included in the latest release (v3.2.0). Is this code for scheduling emails considered stable and production-ready, even though it’s not yet in an official release?

**Comment by kewynakshlley** [comment]
The latest version of the library is available on Maven Central, but we still have to release it on GitHub. It is not a problem at all. The latest version can be used without issues. I will manage to publish the release until the end of the week.

**Comment by Rolet** [comment]
Thank you for the update. Appreciate the quick response
